server:
  shutdown: graceful
#  shutdown: IMMEDIATE
spring:
  profiles:
    active: dev
  #    active: prod #prod environment
  application:
    name: SpringBootDemo
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    enabled: true
